### ISSUE TITLE
Error updating. java.net.MalformedURLException: Illegal character in URL

### ISSUE THREAD

**Issue by atiliosanti** [EsotericSoftware/dnsmadeeasy#2]
Hi, I'm having the following error in several DNS installations:

`2018-02-14 09:28 Error updating.
java.net.MalformedURLException: Illegal character in URL
	at sun.net.www.protocol.http.HttpURLConnection.checkURL(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.<init>(Unknown Source)
	at sun.net.www.protocol.http.Handler.openConnection(Unknown Source)
	at sun.net.www.protocol.http.Handler.openConnection(Unknown Source)
	at java.net.URL.openConnection(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at com.esotericsoftware.dnsmadeeasy.DnsMadeEasy.http(DnsMadeEasy.java:66)
	at com.esotericsoftware.dnsmadeeasy.DnsMadeEasy.update(DnsMadeEasy.java:56)
	at com.esotericsoftware.dnsmadeeasy.DnsMadeEasy$1.run(DnsMadeEasy.java:37)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)`

Do you know what happens?

Thanks!!

**Comment by sahaka** [comment]
I am having the same issue but can't figure out why.

**Comment by NathanSweet** [comment]
This can happen if you have a space in your URL.

**Comment by atiliosanti** [comment]
but I have not modified anything

**Comment by NathanSweet** [comment]
You're right, sorry. Fixed in 1.6 release:
https://github.com/EsotericSoftware/dnsmadeeasy/releases/tag/1.6
